/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as GeRouteImport } from './routes/ge'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminCatalogRouteImport } from './routes/admin.catalog'
import { Route as AdminGeRouteImport } from './routes/admin.ge'
import { Route as AdminGeImportRouteImport } from './routes/admin.ge-import'
import { Route as AdminImportRouteImport } from './routes/admin.import'
import { Route as ProgramsProgramIdRouteImport } from './routes/programs.$programId'
import { Route as AdminProgramsProgramIdRouteImport } from './routes/admin.programs.$programId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const GeRoute = GeRouteImport.update({
  id: '/ge',
  path: '/ge',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCatalogRoute = AdminCatalogRouteImport.update({
  id: '/admin/catalog',
  path: '/admin/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminGeRoute = AdminGeRouteImport.update({
  id: '/admin/ge',
  path: '/admin/ge',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminGeImportRoute = AdminGeImportRouteImport.update({
  id: '/admin/ge-import',
  path: '/admin/ge-import',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminImportRoute = AdminImportRouteImport.update({
  id: '/admin/import',
  path: '/admin/import',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsProgramIdRoute = ProgramsProgramIdRouteImport.update({
  id: '/programs/$programId',
  path: '/programs/$programId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProgramsProgramIdRoute = AdminProgramsProgramIdRouteImport.update({
  id: '/admin/programs/$programId',
  path: '/admin/programs/$programId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/ge': typeof GeRoute
  '/admin/catalog': typeof AdminCatalogRoute
  '/admin/ge': typeof AdminGeRoute
  '/admin/ge-import': typeof AdminGeImportRoute
  '/admin/import': typeof AdminImportRoute
  '/programs/$programId': typeof ProgramsProgramIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/programs/$programId': typeof AdminProgramsProgramIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/ge': typeof GeRoute
  '/admin/catalog': typeof AdminCatalogRoute
  '/admin/ge': typeof AdminGeRoute
  '/admin/ge-import': typeof AdminGeImportRoute
  '/admin/import': typeof AdminImportRoute
  '/programs/$programId': typeof ProgramsProgramIdRoute
  '/admin': typeof AdminIndexRoute
  '/admin/programs/$programId': typeof AdminProgramsProgramIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/ge': typeof GeRoute
  '/admin/catalog': typeof AdminCatalogRoute
  '/admin/ge': typeof AdminGeRoute
  '/admin/ge-import': typeof AdminGeImportRoute
  '/admin/import': typeof AdminImportRoute
  '/programs/$programId': typeof ProgramsProgramIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/programs/$programId': typeof AdminProgramsProgramIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/ge'
    | '/admin/catalog'
    | '/admin/ge'
    | '/admin/ge-import'
    | '/admin/import'
    | '/programs/$programId'
    | '/admin/'
    | '/admin/programs/$programId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/ge'
    | '/admin/catalog'
    | '/admin/ge'
    | '/admin/ge-import'
    | '/admin/import'
    | '/programs/$programId'
    | '/admin'
    | '/admin/programs/$programId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/ge'
    | '/admin/catalog'
    | '/admin/ge'
    | '/admin/ge-import'
    | '/admin/import'
    | '/programs/$programId'
    | '/admin/'
    | '/admin/programs/$programId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  GeRoute: typeof GeRoute
  AdminCatalogRoute: typeof AdminCatalogRoute
  AdminGeRoute: typeof AdminGeRoute
  AdminGeImportRoute: typeof AdminGeImportRoute
  AdminImportRoute: typeof AdminImportRoute
  ProgramsProgramIdRoute: typeof ProgramsProgramIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminProgramsProgramIdRoute: typeof AdminProgramsProgramIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ge': {
      id: '/ge'
      path: '/ge'
      fullPath: '/ge'
      preLoaderRoute: typeof GeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/catalog': {
      id: '/admin/catalog'
      path: '/admin/catalog'
      fullPath: '/admin/catalog'
      preLoaderRoute: typeof AdminCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/ge': {
      id: '/admin/ge'
      path: '/admin/ge'
      fullPath: '/admin/ge'
      preLoaderRoute: typeof AdminGeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/ge-import': {
      id: '/admin/ge-import'
      path: '/admin/ge-import'
      fullPath: '/admin/ge-import'
      preLoaderRoute: typeof AdminGeImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/import': {
      id: '/admin/import'
      path: '/admin/import'
      fullPath: '/admin/import'
      preLoaderRoute: typeof AdminImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/$programId': {
      id: '/programs/$programId'
      path: '/programs/$programId'
      fullPath: '/programs/$programId'
      preLoaderRoute: typeof ProgramsProgramIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/programs/$programId': {
      id: '/admin/programs/$programId'
      path: '/admin/programs/$programId'
      fullPath: '/admin/programs/$programId'
      preLoaderRoute: typeof AdminProgramsProgramIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  GeRoute: GeRoute,
  AdminCatalogRoute: AdminCatalogRoute,
  AdminGeRoute: AdminGeRoute,
  AdminGeImportRoute: AdminGeImportRoute,
  AdminImportRoute: AdminImportRoute,
  ProgramsProgramIdRoute: ProgramsProgramIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminProgramsProgramIdRoute: AdminProgramsProgramIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
