/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GeRouteImport } from './routes/ge'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ProgramsProgramIdRouteImport } from './routes/programs.$programId'
import { Route as AdminProgramsProgramIdRouteImport } from './routes/admin.programs.$programId'

const GeRoute = GeRouteImport.update({
  id: '/ge',
  path: '/ge',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsProgramIdRoute = ProgramsProgramIdRouteImport.update({
  id: '/programs/$programId',
  path: '/programs/$programId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProgramsProgramIdRoute = AdminProgramsProgramIdRouteImport.update({
  id: '/admin/programs/$programId',
  path: '/admin/programs/$programId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/ge': typeof GeRoute
  '/programs/$programId': typeof ProgramsProgramIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/programs/$programId': typeof AdminProgramsProgramIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/ge': typeof GeRoute
  '/programs/$programId': typeof ProgramsProgramIdRoute
  '/admin': typeof AdminIndexRoute
  '/admin/programs/$programId': typeof AdminProgramsProgramIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/ge': typeof GeRoute
  '/programs/$programId': typeof ProgramsProgramIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/programs/$programId': typeof AdminProgramsProgramIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/ge'
    | '/programs/$programId'
    | '/admin/'
    | '/admin/programs/$programId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/ge'
    | '/programs/$programId'
    | '/admin'
    | '/admin/programs/$programId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/ge'
    | '/programs/$programId'
    | '/admin/'
    | '/admin/programs/$programId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  GeRoute: typeof GeRoute
  ProgramsProgramIdRoute: typeof ProgramsProgramIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminProgramsProgramIdRoute: typeof AdminProgramsProgramIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ge': {
      id: '/ge'
      path: '/ge'
      fullPath: '/ge'
      preLoaderRoute: typeof GeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/$programId': {
      id: '/programs/$programId'
      path: '/programs/$programId'
      fullPath: '/programs/$programId'
      preLoaderRoute: typeof ProgramsProgramIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/programs/$programId': {
      id: '/admin/programs/$programId'
      path: '/admin/programs/$programId'
      fullPath: '/admin/programs/$programId'
      preLoaderRoute: typeof AdminProgramsProgramIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  GeRoute: GeRoute,
  ProgramsProgramIdRoute: ProgramsProgramIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminProgramsProgramIdRoute: AdminProgramsProgramIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
